### ISSUE TITLE
Augur.getVotePeriod callback fire twice

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#23] opened 2015-06-27 06:58 UTC
the callback fires twice. once with the correct value, once undefined.

**Comment by tinybike** [comment] 2015-06-27 07:22
I'm having trouble reproducing this.  Can you paste the exact call you're making to getVotePeriod?

**Comment by tinybike** [comment] 2015-07-05 09:35
I was not able to reproduce this error for getVotePeriod, but I did experience this for other methods.  Fixed in d580d5b17e492026665bd2583dc2277a7268ed00; re-open this issue if getVotePeriod continues to have this problem.

**Closed by tinybike** 2015-07-05 09:35 UTC
Labels: bug
