### ISSUE TITLE
Memory issues, firefox crashes, etc.

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#53] opened 2016-04-21 08:04 UTC
Running augurjs in FF will eventually crash it (approx. 8 refreshes). Other browsers show some struggle running it. We should test augurjs piece by piece to isolate where issues may be occurring and resolving them. @tinybike

**Comment by tinybike** [comment] 2016-04-21 10:49
Have you tested this using only augur.js, without all the other UI code running?  I'll start profiling augur.js, but most state is stored in the UI (for both augur1 and augur2 -- the code is different, but augur1 and 2 are both storing the same information and carrying out the same logic) so I think it's worth looking there too.

**Comment by thinkloop** [comment] 2016-04-21 11:58
There's that dummy mode which swaps out augurjs for a dummy service, leaving everything else identical. It runs smooth with no crashes with a lot of settimeout's coming in.

**Comment by tinybike** [comment] 2016-04-22 07:30
Fixed in 838df9428683d27d4a03713df413a1e5a7f1d9c9.

**Comment by thinkloop** [comment] 2016-05-08 20:17
Still happening

**Comment by tinybike** [comment] 2016-05-09 00:30
I can't reproduce this.  When does this happen?  Is it a memory or CPU issue (or both)?  How are you diagnosing it?

**Comment by thinkloop** [comment] 2016-05-09 01:43
For me it's exactly as we originally saw, 7-8 refreshes in FF then console
shows 'out of memory' error. At that point I have to close FF and reopen it.

**Comment by tinybike** [comment] 2016-05-28 21:58
@thinkloop I've tried this on every OS/browser combo I have (including my Windows machine at home) and I can't reproduce this at all.  If this is still happening for you, can you profile it yourself?  If you can identify what's messing things up for you, I'm happy to try and fix it.

**Comment by tinybike** [comment] 2016-06-11 07:24
Was the underlying cause for this the c9 caching issue?  I still cannot reproduce this bug.  Closing for now, but please re-open if you continue to experience!

**Comment by tinybike** [comment] 2016-06-19 04:19
@thinkloop If I understand correctly, you're still experiencing this bug.  I'm re-opening the issue, but fair warning: since I can't reproduce this locally, you'll need to run a CPU profile before I can do anything about it!

**Comment by thinkloop** [comment] 2016-06-27 13:27
@stephensprinkle, @JohnDanz, @priecint, would you mind trying this test:

- visit the most recent augur locally in firefox
- let load for about 10s
- refresh the site, wait 10s again
- repeat 10 times

At some point does the site stop loading, and console says "out of memory" forcing a firefox restart?

What OS are u on?

**Comment by stephensprinkle** [comment] 2016-06-27 15:42
Just conducted the test as outline above + did some memory profiling as I ran the test.

Though it never crashed for me, memory allocation did grown substantially with every reload.  

Screenshot of results:

![screen shot 2016-06-27 at 9 37 08 am](https://cloud.githubusercontent.com/assets/287003/16385775/61ea5bc0-3c4b-11e6-87ea-431be4842368.png)

**Comment by thinkloop** [comment] 2016-06-27 15:53
Any idea what those objects are? How it's possible for memory to increase between refreshes? Only thing I could think of is something with plugins.

**Comment by thinkloop** [comment] 2016-06-27 15:57
btw this doesn't happen to me on linux, it was just a windows thing, I know the rest of you aren't on windows.

**Comment by stephensprinkle** [comment] 2016-06-27 18:36
I spent a bit of time digging into this and it looks to localized to FF (Win + Mac) and I don't yet have a definitive assertion on what is causing the issue.

**Comment by tinybike** [comment] 2017-01-11 21:52
AFAICT this is fixed; @stephensprinkle or others please re-open if you observe this again.

**Closed by tinybike** 2017-01-11 21:52 UTC
Labels: bug, question
